spring.application.name=bankapp
spring.datasource.url=jdbc:mysql://localhost:3306/bankdetail
spring.datasource.username=root
spring.datasource.password=mehak@3103
spring.datasource.driver_class_name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
# secret key
jwt.secret=mysecretkeyisofmaximum32bitsi123456784567890mdjkskdhkdoeuufjrwlsndirhtyiwoendkceiowehcwlieblebcliblhelierfblihe747389yiohfmnm 
jwt.expiration=3600000
spring.autoconfigure.exclude=SeurityAutoConfiguration
server.port=8081